### ISSUE TITLE
Transactions are not supported

### ISSUE THREAD

**Issue by Bazzi1235** [MEDIARITHMICS/liquibase-clickhouse#22]
Hello everyone. 
I'm trying to use your library on a sprig boot(2.5.7) application. This error happens

**error:**
```
[app] Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set db/changesets/1/createTables-clickhouse.yml::create-database::1:
[app]      Reason: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLFeatureNotSupportedException: **Transactions are not supported**
```

It looks like your extension is not being picked up.

**application.yml**
```
spring:
  liquibase:
    url: "jdbc:clickhouse://${ip}:${port}"
    driverClassName: "ru.yandex.clickhouse.ClickHouseDriver"
    change-log: classpath:db/liquibase-click-changelog.yml
```
**liquibase-click-changelog.yml**
```
databaseChangeLog:
  - include:
      file: changesets/1/createTables-clickhouse.yml
      relativeToChangelogFile: true
```

**createTables-clickhouse.yml**
```
databaseChangeLog:
  - changeSet:
      id: 1
      author: 1
      changes:
        - sql: create database if not exist dbname;
```

**gradle:**
```
    implementation 'org.liquibase:liquibase-core:4.3.5'
    implementation group: 'com.mediarithmics', name: 'liquibase-clickhouse', version: '0.7.2'
```
